variable "resource_group_name" {}
variable "nic_name" {}
variable "location" {}
variable "vm_size" {}
variable "vm_name" {}
variable "storage_disk_name" {}
variable "storage_os_name" {}
variable "vnet_name" {}
variable "address_space" {}
variable "sbn_name" {}
